# Generated by Django 4.2.10 on 2026-03-14 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("topic_analysis", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OutlineTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="模板名称")),
                (
                    "style",
                    models.CharField(
                        choices=[
                            ("informative", "信息型"),
                            ("persuasive", "说服型"),
                            ("entertaining", "娱乐型"),
                            ("educational", "教育型"),
                        ],
                        max_length=20,
                        verbose_name="文章风格",
                    ),
                ),
                (
                    "structure",
                    models.JSONField(
                        default=list, help_text="包含章节标题和要点的JSON数组", verbose_name="大纲结构"
                    ),
                ),
                (
                    "applicable_categories",
                    models.JSONField(default=list, verbose_name="适用分类"),
                ),
                (
                    "avg_engagement",
                    models.FloatField(default=0.0, verbose_name="平均互动率"),
                ),
                ("usage_count", models.IntegerField(default=0, verbose_name="使用次数")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否激活")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "大纲模板",
                "verbose_name_plural": "大纲模板",
                "db_table": "outline_templates",
            },
        ),
        migrations.CreateModel(
            name="TitleTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="模板名称")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("news", "新闻类"),
                            ("guide", "指南类"),
                            ("list", "清单类"),
                            ("story", "故事类"),
                            ("question", "问答类"),
                            ("shock", "震惊类"),
                        ],
                        max_length=20,
                        verbose_name="模板分类",
                    ),
                ),
                ("template", models.CharField(max_length=200, verbose_name="模板内容")),
                (
                    "example",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="示例"
                    ),
                ),
                ("avg_ctr", models.FloatField(default=0.0, verbose_name="平均点击率")),
                ("usage_count", models.IntegerField(default=0, verbose_name="使用次数")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否激活")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "标题模板",
                "verbose_name_plural": "标题模板",
                "db_table": "title_templates",
                "ordering": ["-avg_ctr"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("title", "标题"),
                            ("outline", "大纲"),
                            ("summary", "摘要"),
                            ("keywords", "关键词"),
                        ],
                        max_length=20,
                        verbose_name="内容类型",
                    ),
                ),
                ("content", models.TextField(verbose_name="生成内容")),
                ("alternatives", models.JSONField(default=list, verbose_name="备选内容")),
                ("quality_score", models.FloatField(default=0.0, verbose_name="质量分数")),
                (
                    "readability_score",
                    models.FloatField(default=0.0, verbose_name="可读性分数"),
                ),
                (
                    "generation_params",
                    models.JSONField(default=dict, verbose_name="生成参数"),
                ),
                (
                    "user_rating",
                    models.IntegerField(blank=True, null=True, verbose_name="用户评分"),
                ),
                (
                    "user_feedback",
                    models.TextField(blank=True, null=True, verbose_name="用户反馈"),
                ),
                (
                    "generated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="生成时间"),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_contents",
                        to="topic_analysis.topic",
                        verbose_name="话题",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_contents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "生成内容",
                "verbose_name_plural": "生成内容",
                "db_table": "generated_contents",
                "ordering": ["-generated_at"],
                "indexes": [
                    models.Index(
                        fields=["topic", "content_type"],
                        name="generated_c_topic_i_7bee40_idx",
                    ),
                    models.Index(
                        fields=["user", "-generated_at"],
                        name="generated_c_user_id_edeb73_idx",
                    ),
                ],
            },
        ),
    ]
