# Generated by Django 4.2.10 on 2026-03-14 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("topic_analysis", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ABTestExperiment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="实验名称"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="实验描述"),
                ),
                (
                    "control_group_ratio",
                    models.FloatField(default=0.5, verbose_name="对照组比例"),
                ),
                (
                    "experiment_group_ratio",
                    models.FloatField(default=0.5, verbose_name="实验组比例"),
                ),
                ("variables", models.JSONField(default=dict, verbose_name="实验变量")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("running", "运行中"),
                            ("completed", "已完成"),
                            ("paused", "已暂停"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
                ),
                (
                    "ended_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="结束时间"),
                ),
                ("results", models.JSONField(default=dict, verbose_name="实验结果")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "A/B测试实验",
                "verbose_name_plural": "A/B测试实验",
                "db_table": "abtest_experiments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LearningModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="模型名称")),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("user_preference", "用户偏好模型"),
                            ("topic_similarity", "话题相似度模型"),
                            ("recommendation", "推荐模型"),
                        ],
                        max_length=50,
                        verbose_name="模型类型",
                    ),
                ),
                ("version", models.CharField(max_length=50, verbose_name="版本号")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                ("model_file", models.CharField(max_length=500, verbose_name="模型文件路径")),
                ("accuracy", models.FloatField(default=0.0, verbose_name="准确率")),
                ("precision", models.FloatField(default=0.0, verbose_name="精确率")),
                ("recall", models.FloatField(default=0.0, verbose_name="召回率")),
                ("f1_score", models.FloatField(default=0.0, verbose_name="F1分数")),
                (
                    "training_samples",
                    models.IntegerField(default=0, verbose_name="训练样本数"),
                ),
                (
                    "training_time",
                    models.FloatField(default=0.0, verbose_name="训练时长(秒)"),
                ),
                ("is_active", models.BooleanField(default=False, verbose_name="是否激活")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "学习模型",
                "verbose_name_plural": "学习模型",
                "db_table": "learning_models",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ModelPerformanceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metric_name", models.CharField(max_length=50, verbose_name="指标名称")),
                ("metric_value", models.FloatField(verbose_name="指标值")),
                ("sample_size", models.IntegerField(default=0, verbose_name="样本大小")),
                ("details", models.JSONField(default=dict, verbose_name="详细信息")),
                (
                    "recorded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="记录时间"),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_logs",
                        to="feedback.learningmodel",
                        verbose_name="模型",
                    ),
                ),
            ],
            options={
                "verbose_name": "模型性能日志",
                "verbose_name_plural": "模型性能日志",
                "db_table": "model_performance_logs",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="UserFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("click", "点击"),
                            ("like", "点赞"),
                            ("share", "分享"),
                            ("collect", "收藏"),
                            ("skip", "跳过"),
                            ("report", "举报"),
                        ],
                        max_length=20,
                        verbose_name="反馈类型",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="recommendation", max_length=50, verbose_name="反馈来源"
                    ),
                ),
                (
                    "dwell_time",
                    models.IntegerField(blank=True, null=True, verbose_name="停留时间(秒)"),
                ),
                (
                    "scroll_depth",
                    models.FloatField(blank=True, null=True, verbose_name="滚动深度"),
                ),
                ("context", models.JSONField(default=dict, verbose_name="上下文信息")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="topic_analysis.topic",
                        verbose_name="话题",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户反馈",
                "verbose_name_plural": "用户反馈",
                "db_table": "user_feedbacks",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="user_feedba_user_id_e3f6f9_idx",
                    ),
                    models.Index(
                        fields=["topic", "feedback_type"],
                        name="user_feedba_topic_i_b0dd82_idx",
                    ),
                    models.Index(
                        fields=["feedback_type", "created_at"],
                        name="user_feedba_feedbac_34efd8_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ABTestAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        choices=[("control", "对照组"), ("experiment", "实验组")],
                        max_length=20,
                        verbose_name="分组",
                    ),
                ),
                (
                    "assigned_values",
                    models.JSONField(default=dict, verbose_name="分配的变量值"),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="分配时间"),
                ),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="feedback.abtestexperiment",
                        verbose_name="实验",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abtest_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "A/B测试分组",
                "verbose_name_plural": "A/B测试分组",
                "db_table": "abtest_assignments",
                "unique_together": {("experiment", "user")},
            },
        ),
    ]
