# Generated by Django 4.2.10 on 2026-03-14 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("topic_analysis", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecommendationConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="配置名称"),
                ),
                ("cf_weight", models.FloatField(default=0.3, verbose_name="协同过滤权重")),
                (
                    "content_weight",
                    models.FloatField(default=0.3, verbose_name="内容推荐权重"),
                ),
                ("hot_weight", models.FloatField(default=0.2, verbose_name="热门推荐权重")),
                (
                    "trending_weight",
                    models.FloatField(default=0.2, verbose_name="趋势推荐权重"),
                ),
                ("min_score", models.FloatField(default=0.1, verbose_name="最小推荐分数")),
                ("max_items", models.IntegerField(default=20, verbose_name="最大推荐数量")),
                (
                    "diversity_enabled",
                    models.BooleanField(default=True, verbose_name="启用多样性"),
                ),
                (
                    "diversity_lambda",
                    models.FloatField(default=0.5, verbose_name="多样性参数"),
                ),
                (
                    "time_decay_enabled",
                    models.BooleanField(default=True, verbose_name="启用时间衰减"),
                ),
                (
                    "time_decay_factor",
                    models.FloatField(default=0.9, verbose_name="时间衰减因子"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否激活")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "推荐配置",
                "verbose_name_plural": "推荐配置",
                "db_table": "recommendation_configs",
            },
        ),
        migrations.CreateModel(
            name="RecommendationMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日期")),
                (
                    "total_recommendations",
                    models.IntegerField(default=0, verbose_name="总推荐数"),
                ),
                ("total_clicks", models.IntegerField(default=0, verbose_name="总点击数")),
                ("total_likes", models.IntegerField(default=0, verbose_name="总点赞数")),
                ("total_shares", models.IntegerField(default=0, verbose_name="总分享数")),
                ("total_collects", models.IntegerField(default=0, verbose_name="总收藏数")),
                ("ctr", models.FloatField(default=0.0, verbose_name="点击率")),
                ("engagement_rate", models.FloatField(default=0.0, verbose_name="互动率")),
                (
                    "personalized_ctr",
                    models.FloatField(default=0.0, verbose_name="个性化点击率"),
                ),
                ("hot_ctr", models.FloatField(default=0.0, verbose_name="热门点击率")),
                ("trending_ctr", models.FloatField(default=0.0, verbose_name="趋势点击率")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "推荐效果指标",
                "verbose_name_plural": "推荐效果指标",
                "db_table": "recommendation_metrics",
                "ordering": ["-date"],
                "unique_together": {("date",)},
            },
        ),
        migrations.CreateModel(
            name="UserTopicPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preference_score",
                    models.FloatField(default=0.0, verbose_name="偏好分数"),
                ),
                ("click_count", models.IntegerField(default=0, verbose_name="点击次数")),
                ("like_count", models.IntegerField(default=0, verbose_name="点赞次数")),
                ("share_count", models.IntegerField(default=0, verbose_name="分享次数")),
                ("collect_count", models.IntegerField(default=0, verbose_name="收藏次数")),
                ("skip_count", models.IntegerField(default=0, verbose_name="跳过次数")),
                (
                    "first_interacted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="首次互动时间"),
                ),
                (
                    "last_interacted_at",
                    models.DateTimeField(auto_now=True, verbose_name="最后互动时间"),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_preferences",
                        to="topic_analysis.topic",
                        verbose_name="话题",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic_preferences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户话题偏好",
                "verbose_name_plural": "用户话题偏好",
                "db_table": "user_topic_preferences",
                "indexes": [
                    models.Index(
                        fields=["user", "-preference_score"],
                        name="user_topic__user_id_9a14f2_idx",
                    )
                ],
                "unique_together": {("user", "topic")},
            },
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("personalized", "个性化推荐"),
                            ("hot", "热门推荐"),
                            ("trending", "趋势推荐"),
                            ("related", "相关推荐"),
                        ],
                        max_length=20,
                        verbose_name="推荐类型",
                    ),
                ),
                ("score", models.FloatField(default=0.0, verbose_name="推荐分数")),
                ("rank", models.IntegerField(default=0, verbose_name="排名")),
                ("reasons", models.JSONField(default=list, verbose_name="推荐原因")),
                (
                    "feedback",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("click", "点击"),
                            ("like", "点赞"),
                            ("share", "分享"),
                            ("collect", "收藏"),
                            ("skip", "跳过"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="用户反馈",
                    ),
                ),
                (
                    "feedback_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="反馈时间"),
                ),
                (
                    "recommended_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="推荐时间"),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="topic_analysis.topic",
                        verbose_name="话题",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "推荐记录",
                "verbose_name_plural": "推荐记录",
                "db_table": "recommendations",
                "ordering": ["-score"],
                "indexes": [
                    models.Index(
                        fields=["user", "recommended_at"],
                        name="recommendat_user_id_693233_idx",
                    ),
                    models.Index(
                        fields=["topic", "recommendation_type"],
                        name="recommendat_topic_i_b7cc6b_idx",
                    ),
                ],
            },
        ),
    ]
