# Generated by Django 4.2.10 on 2026-03-14 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="数据源名称")),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("rss", "RSS/Atom 订阅"),
                            ("news", "新闻网站"),
                            ("weibo", "微博"),
                            ("zhihu", "知乎"),
                            ("wechat", "微信公众号"),
                            ("bilibili", "B站"),
                            ("twitter", "Twitter"),
                            ("other", "其他"),
                        ],
                        max_length=50,
                        verbose_name="数据源类型",
                    ),
                ),
                ("base_url", models.URLField(verbose_name="基础URL")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "活跃"), ("inactive", "停用"), ("error", "错误")],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "crawl_frequency",
                    models.IntegerField(default=3600, verbose_name="爬取频率(秒)"),
                ),
                (
                    "last_crawled_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="最后爬取时间"),
                ),
                ("total_crawled", models.IntegerField(default=0, verbose_name="总爬取数")),
                ("success_count", models.IntegerField(default=0, verbose_name="成功数")),
                ("error_count", models.IntegerField(default=0, verbose_name="失败数")),
                ("config", models.JSONField(default=dict, verbose_name="爬取配置")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "数据源",
                "verbose_name_plural": "数据源",
                "db_table": "data_sources",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CrawlLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "成功"),
                            ("failed", "失败"),
                            ("partial", "部分成功"),
                        ],
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("items_crawled", models.IntegerField(default=0, verbose_name="爬取数量")),
                ("items_saved", models.IntegerField(default=0, verbose_name="保存数量")),
                (
                    "items_duplicate",
                    models.IntegerField(default=0, verbose_name="重复数量"),
                ),
                ("items_invalid", models.IntegerField(default=0, verbose_name="无效数量")),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                ("duration", models.FloatField(default=0, verbose_name="耗时(秒)")),
                ("started_at", models.DateTimeField(verbose_name="开始时间")),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="结束时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crawl_logs",
                        to="data_collection.datasource",
                        verbose_name="数据源",
                    ),
                ),
            ],
            options={
                "verbose_name": "爬取日志",
                "verbose_name_plural": "爬取日志",
                "db_table": "crawl_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RawContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="标题"
                    ),
                ),
                ("content", models.TextField(verbose_name="内容")),
                ("url", models.URLField(unique=True, verbose_name="原始链接")),
                (
                    "author",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="作者"
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="发布时间"),
                ),
                (
                    "crawled_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="爬取时间"),
                ),
                ("view_count", models.IntegerField(default=0, verbose_name="浏览数")),
                ("like_count", models.IntegerField(default=0, verbose_name="点赞数")),
                ("share_count", models.IntegerField(default=0, verbose_name="分享数")),
                ("comment_count", models.IntegerField(default=0, verbose_name="评论数")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processed", "已处理"),
                            ("invalid", "无效"),
                            ("duplicate", "重复"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="处理状态",
                    ),
                ),
                ("keywords", models.JSONField(default=list, verbose_name="关键词")),
                ("summary", models.TextField(blank=True, null=True, verbose_name="摘要")),
                ("metadata", models.JSONField(default=dict, verbose_name="其他元数据")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contents",
                        to="data_collection.datasource",
                        verbose_name="数据源",
                    ),
                ),
            ],
            options={
                "verbose_name": "原始内容",
                "verbose_name_plural": "原始内容",
                "db_table": "raw_contents",
                "ordering": ["-crawled_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "crawled_at"],
                        name="raw_content_status_9c49ea_idx",
                    ),
                    models.Index(
                        fields=["source", "published_at"],
                        name="raw_content_source__472c5a_idx",
                    ),
                ],
            },
        ),
    ]
