# Generated by Django 4.2.10 on 2026-03-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_collection", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasource",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("rss", "RSS/Atom 订阅"),
                    ("news", "新闻网站"),
                    ("weibo", "微博"),
                    ("zhihu", "知乎"),
                    ("wechat", "微信公众号"),
                    ("bilibili", "B站"),
                    ("xiaohongshu", "小红书"),
                    ("douyin", "抖音"),
                    ("twitter", "Twitter"),
                    ("other", "其他"),
                ],
                max_length=50,
                verbose_name="数据源类型",
            ),
        ),
    ]
