# Generated by Django 4.2.10 on 2026-03-14 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("data_collection", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="话题名称"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="话题描述"),
                ),
                ("keywords", models.JSONField(default=list, verbose_name="关键词")),
                ("main_keyword", models.CharField(max_length=100, verbose_name="主关键词")),
                ("heat_score", models.FloatField(default=0.0, verbose_name="热度分数")),
                (
                    "trend",
                    models.CharField(
                        choices=[("rising", "上升"), ("falling", "下降"), ("stable", "稳定")],
                        default="stable",
                        max_length=20,
                        verbose_name="趋势",
                    ),
                ),
                ("article_count", models.IntegerField(default=0, verbose_name="文章数量")),
                ("view_count", models.IntegerField(default=0, verbose_name="总浏览数")),
                ("engagement_rate", models.FloatField(default=0.0, verbose_name="互动率")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "活跃"),
                            ("inactive", "不活跃"),
                            ("trending", "热门"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "first_seen_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="首次发现时间"),
                ),
                (
                    "last_updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="最后更新时间"),
                ),
                (
                    "related_topics",
                    models.ManyToManyField(
                        blank=True, to="topic_analysis.topic", verbose_name="相关话题"
                    ),
                ),
            ],
            options={
                "verbose_name": "话题",
                "verbose_name_plural": "话题",
                "db_table": "topics",
                "ordering": ["-heat_score"],
            },
        ),
        migrations.CreateModel(
            name="TopicCluster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="聚类名称")),
                (
                    "center_keywords",
                    models.JSONField(default=list, verbose_name="中心关键词"),
                ),
                (
                    "coherence_score",
                    models.FloatField(default=0.0, verbose_name="一致性分数"),
                ),
                ("total_articles", models.IntegerField(default=0, verbose_name="总文章数")),
                ("total_views", models.IntegerField(default=0, verbose_name="总浏览数")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "topics",
                    models.ManyToManyField(
                        related_name="clusters",
                        to="topic_analysis.topic",
                        verbose_name="包含话题",
                    ),
                ),
            ],
            options={
                "verbose_name": "话题聚类",
                "verbose_name_plural": "话题聚类",
                "db_table": "topic_clusters",
            },
        ),
        migrations.CreateModel(
            name="TopicTrend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recorded_at", models.DateTimeField(verbose_name="记录时间")),
                ("heat_score", models.FloatField(verbose_name="热度分数")),
                ("article_count", models.IntegerField(verbose_name="文章数量")),
                ("view_count", models.IntegerField(verbose_name="浏览数")),
                ("engagement_rate", models.FloatField(verbose_name="互动率")),
                ("growth_rate", models.FloatField(default=0.0, verbose_name="增长率")),
                ("velocity", models.FloatField(default=0.0, verbose_name="速度")),
                ("acceleration", models.FloatField(default=0.0, verbose_name="加速度")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trends",
                        to="topic_analysis.topic",
                        verbose_name="话题",
                    ),
                ),
            ],
            options={
                "verbose_name": "话题趋势",
                "verbose_name_plural": "话题趋势",
                "db_table": "topic_trends",
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["topic", "recorded_at"],
                        name="topic_trend_topic_i_1c837d_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ContentTopicRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relevance_score",
                    models.FloatField(default=0.0, verbose_name="相关性分数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic_relations",
                        to="data_collection.rawcontent",
                        verbose_name="内容",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_relations",
                        to="topic_analysis.topic",
                        verbose_name="话题",
                    ),
                ),
            ],
            options={
                "verbose_name": "内容话题关联",
                "verbose_name_plural": "内容话题关联",
                "db_table": "content_topic_relations",
                "indexes": [
                    models.Index(
                        fields=["topic", "relevance_score"],
                        name="content_top_topic_i_9e863f_idx",
                    )
                ],
                "unique_together": {("content", "topic")},
            },
        ),
    ]
